"""initial schema

Revision ID: 130edb950479
Revises: 
Create Date: 2026-07-23 12:19:53.644157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130edb950479'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_scanned_url', sa.String(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rubric_versions',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('family_weights', sa.JSON(), nullable=False),
    sa.Column('check_weights', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('ars', sa.Integer(), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('requester_ip_hash', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_normalized_url'), 'scans', ['normalized_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_normalized_url'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('rubric_versions')
    op.drop_table('leads')
    # ### end Alembic commands ###
